sudo apt install build-essential
sudo apt install libasio-dev
sudo apt install ros-melodic-teleop-twist-keyboard
sudo apt install ros-melodic-ros-control
sudo apt install ros-melodic-ros-controllers
sudo apt install ros-melodic-joint-state-publisher-gui 
sudo apt install ros-melodic-robot-state-publisher 
sudo apt install ros-melodic-roslint
sudo apt install ros-melodic-teleop-twist-joy
sudo apt install ros-melodic-move-base
sudo apt install ros-melodic-rqt 
sudo apt install ros-melodic-rqt-common-plugins
sudo apt install ros-melodic-rqt-robot-plugins 
sudo apt install ros-melodic-rqt-robot-steering
sudo apt install ros-melodic-dwa-local-planner
sudo apt install ros-melodic-lms1xx
sudo apt install ros-melodic-velodyne-description
sudo apt install ros-melodic-realsense2-camera
sudo apt install ros-melodic-realsense2-description
sudo apt install ros-melodic-robot-localization
sudo apt install ros-melodic-interactive-marker-twist-server
sudo apt install ros-melodic-twist-mux
sudo apt install ros-melodic-joy
sudo apt install ros-melodic-teleop-twist-joy
sudo apt install ros-melodic-pointcloud-to-laserscan
sudo apt install ros-melodic-imu-filter-madgwick
sudo apt install ros-melodic-rviz-imu-plugin

