sudo apt install -y build-essential
sudo apt install -y libasio-dev
sudo apt install -y lua5.2
sudo apt install -y liblua5.2-dev
sudo apt install -y libceres-dev
sudo apt install -y ros-$ROS_DISTRO-teleop-twist-keyboard
sudo apt install -y ros-$ROS_DISTRO-ros-control
sudo apt install -y ros-$ROS_DISTRO-ros-controllers
sudo apt install -y ros-$ROS_DISTRO-joint-state-publisher-gui 
sudo apt install -y ros-$ROS_DISTRO-robot-state-publisher 
sudo apt install -y ros-$ROS_DISTRO-roslint
sudo apt install -y ros-$ROS_DISTRO-teleop-twist-joy
sudo apt install -y ros-$ROS_DISTRO-move-base
sudo apt install -y ros-$ROS_DISTRO-rqt 
sudo apt install -y ros-$ROS_DISTRO-rqt-common-plugins
sudo apt install -y ros-$ROS_DISTRO-rqt-robot-plugins 
sudo apt install -y ros-$ROS_DISTRO-rqt-robot-steering
sudo apt install -y ros-$ROS_DISTRO-dwa-local-planner
sudo apt install -y ros-$ROS_DISTRO-lms1xx
sudo apt install -y ros-$ROS_DISTRO-velodyne-description
sudo apt install -y ros-$ROS_DISTRO-realsense2-camera
sudo apt install -y ros-$ROS_DISTRO-realsense2-description
sudo apt install -y ros-$ROS_DISTRO-robot-localization
sudo apt install -y ros-$ROS_DISTRO-interactive-marker-twist-server
sudo apt install -y ros-$ROS_DISTRO-twist-mux
sudo apt install -y ros-$ROS_DISTRO-joy
sudo apt install -y ros-$ROS_DISTRO-teleop-twist-joy
sudo apt install -y ros-$ROS_DISTRO-pointcloud-to-laserscan
sudo apt install -y ros-$ROS_DISTRO-imu-filter-madgwick
sudo apt install -y ros-$ROS_DISTRO-rviz-imu-plugin
sudo apt install -y ros-$ROS_DISTRO-gmapping
sudo apt install -y ros-$ROS_DISTRO-amcl
sudo apt install -y ros-$ROS_DISTRO-map-server
sudo apt install -y ros-$ROS_DISTRO-octomap-rviz-plugins
sudo apt install -y ros-$ROS_DISTRO-fake-localization
