export SCOUT_CAMREA_PREFIX="/realsense"

export SCOUT_YDLIDAR_ENABLED=1
export SCOUT_LASER_TOPIC="/scan"
#export SCOUT_LASER_TOPIC="$SCOUT_CAMREA_PREFIX/scan"
export SCOUT_LASER_3D_ENABLED=0
export SCOUT_REALSENSE_ENABLED=1

export SCOUT_SENSOR_ARCH_HEIGHT=510